### ISSUE TITLE
Add some default recipes

### ISSUE THREAD

**Issue by aburone** [CompactMods/CompactCrafting#44]
I'm playing with a custom modpack where I only touch things when they're blatantly incompatible with one another.

I want to use the compact crafting mechanic for the compact machines, but not having default crafting recipes makes that impossible.
Thanks

**Comment by ghost** [comment]
Hello, you can modify the recipes with datapacks or KubeJS or CraftTweaker.
The wiki can also help you : https://github.com/CompactMods/CompactCrafting/wiki
You can look in the 'src' folder I think **robotgryphon** has left some tests or examples.
And there is a discord I think someone can help you.

Otherwise there is another repo with recipes : https://github.com/CompactMods/compact-recipes

**Comment by aburone** [comment]
Oh, I didn't know that other repo existed! Downloading.
Might be good to mention it on the Forge page.

Yes, I know I could use datpacks and the like. But I prefer to spend my time playing inside my world than writing scripts

**Comment by robotgryphon** [comment]
As already mentioned, CC is meant to be a hands-off mod that a pack maker should explicitly build support for, given that it's a mod whose only goal is to add the new crafting mechanic - nothing else. Given global datapack mods and things like KubeJS, I plan to continue being opt-in on CC/CM4 integration.

If you want to discuss over Discord, there's a link on the repo main README that'll get you there. For now, closing this.
